apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: developer
spec:
  request: # Put your base64 encoded certificate here.
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth